### ISSUE TITLE
[BUG] Can not show linear regress

### ISSUE THREAD

**Issue by mocowo** [michaeldmoore/michaeldmoore-scatter-panel#14]
![image](https://user-images.githubusercontent.com/36118268/126099728-cb77603e-fab0-410e-959f-fa300df37bbc.png)

installed grafana-7.5.6-1.x86_64.rpm 
I use grafana global variables to show two dataset. One dataset shows right, but another shows wrong as the above picture.

**Comment by michaeldmoore** [comment]
Interesting - maybe something to do with the number of points?

I'm going to be very busy for the next few weeks so this might take a while
to get around to addressing this.  In the meantime, can you export the data
to CSV and post it here so I've got something to work on?


Also - I don't think this is related in any way - but there is a known bug
that appears when there is more than one copy of the Scatter plugin panel
on a single dashboard.  Some of the settings for the second panel end up
being applied to the first panel.  I mention this as your note said
something about the first panel being OK. The problem here appears to be in
Grafana itself, so I'm waiting for them to fix it.

Actually, re-reading your note more carefully, I'm wondering if this
applies to any linear regressions with multiple data sets.

Can you filter your data in any way, to have a small number of data points
- say 10 or so - in each set?  I did most of my development work with such
tiny data sets and your test would confirm whether this is related to the
large number of data points or something more basic.

Michael Moore

**Comment by mocowo** [comment]
Thanks for your quick feedback. And thanks to your prompt, I found out where is the problem.
As you see below dataset, the qps number may be too large. When I use qps/10, the line becomes right.

Hope your efforts to fix it.

qps | cpu_usage | mem_usage
-- | -- | --
10203 | 36 | 10.8
3421 | 15 | 12.4
8796 | 58 | 12.2
5918 | 22 | 12.1
2343 | 9 | 12.0
2269 | 10 | 12.1
9301 | 36 | 10.8
8974 | 34 | 10.6
8090 | 34 | 10.5
8783 | 33 | 10.5
7444 | 38 | 12.4
4399 | 18 | 11.8
8161 | 34 | 10.6
9556 | 51 | 12.1
8799 | 36 | 10.8
10320 | 50 | 12.1
9095 | 35 | 10.7
9378 | 33 | 10.6
2344 | 9 | 12.1
10611 | 57 | 12.1
8588 | 33 | 10.7
6477 | 32 | 12.2
8279 | 35 | 10.6
6553 | 26 | 12.2
7762 | 36 | 12.3
7337 | 37 | 12.4
12892 | 52 | 12.0

**Comment by michaeldmoore** [comment]
I don't know if I did anything about this, but just as I'm getting ready to release version 1.2.0 with a bunch of other enhancements - I tried your data set and it seems to work perfectly.
