### ISSUE TITLE
Scatter X Axis Extent Min & Max are not getting Updated after a change.

### ISSUE THREAD

**Issue by sarangsmk** [michaeldmoore/michaeldmoore-scatter-panel#17]
I have 2 Scatter elements or Panels in my Dashboard.
Scatter S1, S2 and visualizing some data from MySql datasource.
In S2 I have set X-Axis Extent Min & Max to value: S2V1 and value: S2V2
And for S1 I have set X-Axis Extent Min & Max to value: S1V1 and value: S1V2
But after a dashboard refresh, the S2 have saved X-Axis Extent Min & Max values that is S2V1 and S2V2, But S1 doest have the saved _**values S1V1 and S1V2 but have S2V1 and S2V2 instead.**_

Having 2 or more Scatter elements will cause issues..?

Grafana Version: Grafana v8.2.1 (88622d7f09) : OSS
Scatter Version: Latest
Server OS: Windows 10
Client OS: Windows 10
Client Browser: Google Chrome

**Comment by OverWorldD** [comment]
Is this related to the fact that the values sometimes do not respect the max and min that have been set for an axis? In this case the values overshoot my X-axis endstop.
![image](https://user-images.githubusercontent.com/12225528/151972527-806351d6-1e8e-49e3-9f3a-9773f6f9a539.png)

**Comment by michaeldmoore** [comment]
Yes and no.

The bigger problem happened whenever a dashboard had two or more Scatter
panels - after saving and reloading, many of the configuration settings
were being over-written.  This appears to have been a problem with Grafan
itself, as the latest version of grafana no longer show this problem.

On the other hand, I did have a problem with the masking process that
should hide items outside the area defined by the extents.  I cured this
and a number of other issues in the latest update (v1.1.0), along with a
few handy enhancements.  This release is still in the release pipeline, so
for the moment the only way to get it is from the git repository.  I've
been very slow in getting the release approved - too many distractions, I'm
afraid.  You should see the newer, fixed, version soo in the official
grafana plugin repository.

Best wishes
Michael Moore

**Comment by OverWorldD** [comment]
Hi Michael, thank you for the prompt response! I am also experimenting with the XYChart plugin that you mentioned, and I have gotten that to work but there I have problems with the X-axis not scaling at all to my Min and Max values. (I filed a different bug report for that) I'm running Grafana 8.3.3 but I see now that there is an 8.3.4 so I'll try and see if that helps both these issues.

And thank you again for your plugins!

**Comment by michaeldmoore** [comment]
Just to set your expectations.  New versions of Grafana fix the multiple
scatter panel configuration corruption issue.  I don't know when this fix
was implemented, but I think it was well before your current version.

On a separate issue - the extent point clipping bug is one I have fixed in
scatter-panel v1.1.0 which is waiting approval, so not yet available from
the Grafana panel repo.  Right now, Scatter v1.1.0 is only available here
in my git repo.  Once it gets through Grafana's approval process, it will
be listed on the official repo.  For the moment though, the official repo
only has Scatter version v1.0.0 which has the clipping bug you ran into.

Hope that is clear enough.
MM

P.S.  I'm impressed with the data set you showed in the COP/Brine temp
chart.   Any chance of getting a csv file with this data?  Assuming it's
not terribly proprietary data, it would be a much better sample data set
for my testing and demonstration.

**Comment by OverWorldD** [comment]
Hi! Okay, is it possible to install the v1.1.0 from your github or will grafana block it?
Sure you could have my data, but it's from influx and I don't know how to export it, but I'll try!

**Comment by michaeldmoore** [comment]
Good point.  The v1.1.0 up there is unsigned.

If you own the server, you can set the app mode from production to
development in the Grafana config file - that will allow unsigned panels.
That should do for the time being.

And thanks for the CSV data set too.
M

**Comment by OverWorldD** [comment]
Hi! Nice to hear you got the CSV, I have the server running here locally so I can edit the config! I'll do that, thanx!
By the way, one thing I like in XY Chart is the mouseover legend that pops up, so I can instantly check a value. I did not see any setting for that in Scatter 1.0 - maybe it is in 1.1.0, if not - feature request. It's very handy to be able to check on an outlier, and then get the timeframe to go into the other data and see what was going on.

**Comment by michaeldmoore** [comment]
Tooltips, yes.  Not in this version, I'm afraid.  It is much more
complicated to do right than one might imagine.  I added tooltips like this
to my Mutistat panel, then someone requested to be able to copy and paste
the text from the tool-tip.  Turns out this is really tricky.  i got it
working eventually, but now understand why no one else allows the tool-tip
data to be selectable for copy-and-paste.

Oh well.  Maybe I'll add this in an upcoming release of scatter too.  I was
kind of hoping the XYChart panel would make Scatter redundant and this I
could just let it go to rust etc.

**Comment by OverWorldD** [comment]
I see, and I think XYChart will eventually be good too, I'd say right now they are at par with each other from a usability standpoint. I find Scatter easier to work with, XYChart still has some quirks - I just posted a bug that the min-max scale is not working, but it turned out that function was still blank in the code so no wonder :) There is a reason it is not available in Grafana yet :)
