### ISSUE TITLE
Wishlist: data label

### ISSUE THREAD

**Issue by OccRazor** [michaeldmoore/michaeldmoore-scatter-panel#2]
Hi!
Great to have a simple X-Y panel. Could I please add a feature request:
Could we have a column of data with strings used as labels for data points?

Thanks & best regards,
O.

**Comment by michaeldmoore** [comment]
Let me understand this better.

Is this just for the X axis?, so instead of just using a numerical value to
define the distance along the axis, we'd also write a tick-point and a
label based on the string in some other value?  Definitely an interesting
idea and I can see how this might be useful.

Maybe too, the X-value column itself could be dispensed with. - If we had
an array of labels, the display the X value corresponding to the position
in the label array.


I had a feature request for my bar chart panel - multistat - to arrange the
bars like a race award podium - arranged as 3rd, 1st and 2nd.  That was too
far from the main concept of that panel to be included, but with your idea
- if I understand it correctly, all I'd need to do is display the results
as bars instead of points and/or lines.  Very interesting.

If you are interested, drop me a sample mock up of a data set and the
imagined resulting display you have in mind.

No promises
Michael Moore

**Comment by OccRazor** [comment]
Thanks for coming back on this.
X-Axis by categories could be useful for a number of things, but I was thinking along the idea of data labels within the plot space.
I have been trying to put something together using the AE3E plotly panel (below), that shows some texts on the data points themselves.
![Grafana-AE3E-Plotly](https://user-images.githubusercontent.com/80403540/110803408-7298b500-827f-11eb-9ac7-775e4e471e32.png)
This is going into the right direction (with a lot of effort on part of the user), but I would like some more control over the labels (bounding box size, text direction, box and frame color, above or below data or even transparency would be great). Maybe one could do it with plotly labels, given time.
[DataFrame.zip](https://github.com/michaeldmoore/michaeldmoore-scatter-panel/files/6123781/DataFrame.zip)
The labels of this frame should be a bit more descriptive, I just pulled some automated tags here for illustration. For my data the plotly hovertext frames but oriented vertically above or below the datapoint (depending on vertical placement) would be optimal, I guess, but mainly I would want them fixed in place, rather than showing up on hover. Should I try and 'shop the screenshot?

Cheers,
Oliver Schoen

**Comment by michaeldmoore** [comment]
Sorry for not getting back to you sooner on this.  No excuses other than laziness on my part, I'm afraid.

I understand your idea and will give it serious consideration next time I work on an enhancement release.  Right now, I'm about to release version 1.2.0 with a number of user-requested enhancements. Yours though is sadly not going to be one of them this time.

M
