### ISSUE TITLE
scatter

### ISSUE THREAD

**Issue by Chengminshu** [michaeldmoore/michaeldmoore-scatter-panel#29]
Hello, may I ask why the x-axis of the scatter panel I downloaded from the official website shows the timestamp instead of the time
![image](https://user-images.githubusercontent.com/54847848/146293441-c73ecb8c-44e7-4d4d-87f2-788928e9acb1.png)

**Comment by michaeldmoore** [comment]
Your data query must be returning a Unix timestamp (i.e., seconds from Bill
Gates' birthday, or something ) instead of an actual, date.  Scatter
displays whatever the column data says.  Try switching the visualization to
the Table panel to see what it is actually dealing with.

On the other hand, Scatter needs the something numeric to know how far from
the left to draw the point.

Generally, if you want to draw points with a time axis along the bottom,
you'll be much better off using the built-in Graph panel, though you would
need to change the query into a time-series query.

I have an updated version of Scatter that deals with some of the things you
a running into, particularly in this case, the ability to define a
different column for the labels (so you might have both the Unix seconds
column and a date formatted column.  Depending on your data, this might
work for you.  Right now though, it's waiting for Grafana to approve and
release this updated version which can take a month or more.

Another idea.  Grafana has a similar panel called XYChart, but as far as I
know, it needs something in the configuration file to enable it.  I haven't
seen it working myself, but poke around and see if this works better.

If all else fails, use the query inspector to export your data as a CSV
file and send it to me, ong with the panel JSON and I'll see what I can do
with it.

**Comment by Chengminshu** [comment]
sir,
At present, the number of seconds is also here, but it seems that it has not been converted into time. At present, this plug-in does not support it
![image](https://user-images.githubusercontent.com/54847848/146476718-86c36bb2-0afa-4779-b48a-8046d66e9693.png)
