### ISSUE TITLE
I am forced to add time column

### ISSUE THREAD

**Issue by aya-givati** [michaeldmoore/michaeldmoore-scatter-panel#36]
I created a table identical to the one from the example in mysql.
![image](https://user-images.githubusercontent.com/54662189/161423710-82256857-7ff5-4796-a42e-d47b689cceb8.png)

when I try to select the data I get an error _db has no time column: no time column found_
![image](https://user-images.githubusercontent.com/54662189/161423872-302bae34-1512-4b27-a3f0-c0a0dc4f5acd.png)

so I added a dummy time column (the value is always 1) and it worked - but id doesn't make any sense...
![image](https://user-images.githubusercontent.com/54662189/161423458-f182050e-8393-40cf-a2c2-f4498e60e6f5.png)

why is it happens?
(I am using grafana cloud)

==========================================================
If you can solve me this problem, the next one is harder.
my data  actually looks like that:
![image](https://user-images.githubusercontent.com/54662189/161423694-1f08473f-78d4-4c34-bd5b-830487302b65.png)
and there can be more that just 2 genders (all the LGBTQ..) - so I need that the number of series will be decided dynamically based on the data (it works on time series panel)
Can it be done?

Thank you!,
Aya

**Comment by michaeldmoore** [comment]
Grafana supports two kinds of data formats - time series and tables.
 Time series data (such as used in the built-in graph panel) MUST have a
UNIX-timestamp column called 'time'.

The scatter panel works with TABLE formatted data sets, which do not have
any such requirement.  So get rid of the unused 'Age' field in your query
and select TABLE format.  It should work as you expect.

Additionally, the Scatter panel works with unlimited numbers of values.
Each column can be displayed as a separate colour/line.  Press the 'add
fieldset' (or whatever it's called' to add as many columns as you want.

Reply if any of this is not clear, I'll be glad to walk you through it.

**Comment by aya-givati** [comment]
Hi @michaeldmoore  - thank you for your quick reply.

1) Got it :) 
I confused table format with table view..

2) my problem that I do not know in advance how many columns I am about to have - the number of columns is dynamic.
the data can look like these (I switch from gender to animals... it easier...)
![image](https://user-images.githubusercontent.com/54662189/161427188-2d3e2b99-789e-497e-bbc5-4ae43253a2c3.png)
or like these
![image](https://user-images.githubusercontent.com/54662189/161427232-40201db9-bad2-40c5-8115-4af3044e5a84.png)
or like these
![image](https://user-images.githubusercontent.com/54662189/161427359-6f24ef0c-39d1-4917-bb2b-e28930ac5b35.png)
  
is there a way to do the series dynamic?


Thank you!

**Comment by michaeldmoore** [comment]
Interesting.  Someone sent in a question very similar to this some time ago
(maybe you?).  If so, sorry for not responding properly at the time.

A couple of things.
As it stands, I have no way of assigning the values to a series based on
the value of some ID column as you suggest.

What could work is if you can rearrange the data (either in the query or
maybe using some sort of Grafana data transformation (I haven't looked much
into this, so it might not be possible)
If you could make the data look something like this:

*Age* *Lion* *Frog* *Mouse*
1 60 65 56
2 70 75 65




or






*Age* *Lion* *Frog* *Mouse*
1 60

1
65
1

56
2 70

2
75
2

65

It should work the way you want.  In the second example, the blanks are
nulls which won't appear in the plot.


Also, while these are not exactly dynamic columns, you could create a data
set with some upper limit of categories (i.e. columns), then configure the
panel to give each the desired characteristics (colors, size, line tyes etc
etc).  Then when an actual data set is presented with some lesser number of
categories, the unused lines - being absent, these should ll be treated
internally as nulls (I think).  The missing categories should just
disappear.

There might be some weirdness regarding the legends - the missing
categories would probably create empty legend entries.  Still, it's worth a
shot.

Good luck and let me know how this turns out.
