### ISSUE TITLE
Incorrect X axis and Null handeling

### ISSUE THREAD

**Issue by JohnBolander** [michaeldmoore/michaeldmoore-scatter-panel#44]
The scatter plugin is pretty sweet, but it seems to not be plotting x axis correctly. Despite selecting the column, it is plotting it vs row number instead (the highest c\device_id value is ~2 for example). It also is plotting the null values as 0 as opposed to ignoring them. See image below. I'm on Scatter Plugin 1.2.0 and Grafana 8.5.1.

![image](https://user-images.githubusercontent.com/4633707/221329158-934c46f2-539b-4d05-ad1b-4bae5884e350.png)

![image](https://user-images.githubusercontent.com/4633707/221329089-982129db-b937-4ebe-b824-fa1608001269.png)

**Comment by michaeldmoore** [comment]
How odd.

Just guessing here, but check to see if these are number fields, and not
strings.  And null rather than an empty string.  Just guessing.

Also, any chance you have more than one column called c\device_id?

If you're still getting this, can you upload the panel JSON and a data
sample (as a csv file) so I can try it out.

**Comment by JohnBolander** [comment]
Ok, I figured out the problems after you suggested looking at field types. The problem with the c\device_id was that Grafana made it a string column when I used the "Grouping to matrix" transform (fixed with type conversion transform). The problem with the 0 plotting when there is no data was that Grafana made no data "" instead of Null in my version (again using the transform). The latest version addresses this issue, so I will have to update. Thank you for your quick response!

**Comment by michaeldmoore** [comment]
Glad it worked!

I was worried about the null issue, but as you say - that was with an older
version.

I'm going to look into the c\device_id as string issue.  This seems like
something that should work after all.  I don't understand why it turned
into an ordinal - that seems weird.  With the current version, I don't
think it would allow non-numeric columns to be defined as x or Y values.
Internally, it stored the column identifiers using their column numbers
rather than the names, but it populates the configuration drop downs with
the names (eliminating any with non-numeric data types).  Maybe it seems to
be working if you did the configuration with the older version (that didn't
worry about column types) and now use the more up-to-date version that does.
On the other hand, maybe this filtering of the column names for numeric
fields issue is only in my current development branch.
I'm thinking, it might be useful to figure out possible numeric fields by
actually looking through the data values  - if they can all be converted to
numbers, then the field could be seen as a numeric field even if the
underlying data type is a string.  The downside to all this is the possible
significant extra computation needed every time a new data set is
received.  Most of my actual uses of the panel is for monitoring fast(ish)
moving data sets - updating every few seconds.  Something to think about.

Don't hold your breath though, it doesn't seem like a priority issue as
no-one else has mentioned it.

Cheers, and thanks for the update.  Don't hesitate to add anything you find
missing, or incomprehensible in the panel or the documentation.
M
